### ISSUE TITLE
Broke

### ISSUE THREAD

**Issue by ghost** [TerableCoder/Endless-Crafting#5]
So,
Patch 88 broke it. 
Its not using cures. 

Not sure whats breaking it. 

All my defs/op-codes are mapped. assumed something in the update broke it.

fyi
S_FATIGABILITY_POINT 62356

protocol version 359881 (NA v88.4).

**Comment by QuestionableUser** [comment]
fyi
S_FATIGABILITY_POINT 62356

protocol version 359881 (NA v88.4).

**Comment by ghost** [comment]
It will craft as normal, that much works. 
i have to manually consume cures though.
